### ISSUE TITLE
clone下来后, 这样运行对嘛

### ISSUE THREAD

**Issue by heise100** [hepengwei/visualization-collection-vue#25]
node版本:v16.20.1
1. npm install 不成功, 后尝试用阿里代理"npm install --registry=https://registry.npmmirror.com" 还是不成功
![image](https://github.com/hepengwei/visualization-collection-vue/assets/3273010/5dbeb71e-eb8d-4a7b-8a7e-aa2034dbf3fc)

2. 之后执行:npm run dev
![image](https://github.com/hepengwei/visualization-collection-vue/assets/3273010/7f4fda34-c606-4e40-938d-2cb88f16a254)

**Comment by hepengwei** [comment]
翻墙试试，国内网有可能有的依赖下载不下来

**Comment by Zhzxiansheng** [comment]
我也遇到了这个问题，我翻墙了，也不行

**Comment by Zhzxiansheng** [comment]
我也遇到了这个问题，翻墙了也不行
是node 版本问题吗？ 我从v16.17.0  切换到了 v18.7.0 也不行
![image](https://github.com/hepengwei/visualization-collection-vue/assets/22702616/04c997b7-ae22-4ff6-8ec4-c3add030abd1)

**Comment by hepengwei** [comment]
刚才我试了，重新安装依赖启动没有问题，使用yarn命令安装，项目中有yarn.lock文件，node v16.18.0

**Comment by heise100** [comment]
运行成功了, 用阿里镜像 "yarn install --registry=https://registry.npmmirror.com"
