### ISSUE TITLE
类型 "typeof import("/Users/....l/node_modules/sphere-collision/types/index")" 没有构造签名。ts(2351)

### ISSUE THREAD

**Issue by nivaner** [hepengwei/visualization-collection-vue#29]
import SphereCollision from 'sphere-collision'
import type { SphereCollisionC, GlobuleC } from 'sphere-collision/types'

 this.sphereCollision2 = new SphereCollision( ctx2, canvas2, ...)

此表达式不可构造。
  类型 "typeof import("/Users/....l/node_modules/sphere-collision/types/index")" 没有构造签名。ts(2351)

**Comment by hepengwei** [comment]
请问你是在自己项目中使用sphere-collision库吗？完整的代码能看下吗？
