### ISSUE TITLE
建议增加vite-plugin-vue-inspector配置，方便本地调试

### ISSUE THREAD

**Issue by xingyixiang** [hepengwei/visualization-collection-vue#42]
[vite-plugin-vue-inspector](https://github.com/webfansplz/vite-plugin-vue-inspector#readme)

**Comment by hepengwei** [comment]
> [vite-plugin-vue-inspector](https://github.com/webfansplz/vite-plugin-vue-inspector#readme)

这个东西你在你本地安装使用就行了，不是所有人都有调试的需求的
