### ISSUE TITLE
安装依赖问题

### ISSUE THREAD

**Issue by weizhigang55** [hepengwei/visualization-collection-vue#43]
强大的大佬呀，想问下为什么node版本使用指定的20.3.1用npm安装还是安装了依赖，报了一堆无法安装，但是用yarn可以安装，想了解下为什么
 weizhigang@wangerdandeMacBook-Pro visualization-collection-vue % npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: visualization-collection-vue@1.0.0
npm ERR! Found: @tensorflow/tfjs-backend-webgl@4.8.0
npm ERR! node_modules/@tensorflow/tfjs-backend-webgl
npm ERR!   @tensorflow/tfjs-backend-webgl@"^4.8.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @tensorflow/tfjs-backend-webgl@"^3.13.0" from @tensorflow-models/body-segmentation@1.0.1
npm ERR! node_modules/@tensorflow-models/body-segmentation
npm ERR!   @tensorflow-models/body-segmentation@"^1.0.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/weizhigang/.npm/_logs/2024-02-22T09_48_13_823Z-eresolve-report.txt

**Comment by hepengwei** [comment]
该项目就是用yarn安装的依赖，有yarn.lock文件，node用v16版本，至于为什么无法安装就不清除了
