### ISSUE TITLE
关于实用功能=>证件照

### ISSUE THREAD

**Issue by weizhigang55** [hepengwei/visualization-collection-vue#44]
大佬想问下为什么实用功能中的拍证件照功能，点击准备拍照为什么反应偏慢，比录像要慢上不少，这个是什么原因

**Comment by hepengwei** [comment]
我试了不会很慢，可能是你点的时候页面还没加载完全

**Comment by hepengwei** [comment]
我试了不会很慢，可能是你点的时候页面还没加载完全

**Comment by weizhigang55** [comment]
看了下代码了解嘞，这个好像要加载一个模型，这个模型好像加载好像还需要开着梯子才可以，谢谢大佬了
