### ISSUE TITLE
Hello，有没有计划做页面调试和复制代码，类似 uiverse.io

### ISSUE THREAD

**Issue by kkll2333** [hepengwei/visualization-collection-vue#52]
![image](https://github.com/user-attachments/assets/8c7d62c2-4195-4240-958d-3229631b1313)

**Comment by hepengwei** [comment]
因为该项目整体是使用Vue实现的，不是只有HTML和CSS文件， 一个Vue页面或组件里（在这里就是每个案例）不光是只有该案例对应的文件或文件夹中的代码，它还引入了很多其他文件夹或文件中的方法，比如：可能会引入公共组件文件夹components中的某个组件，会引入公共hooks文件，还会引入公共的工具方法文件夹utils中的某个方法，还有的会使用全局的变量或sass变量，等等这些，那么如果将每个案例文件夹中对应的.vue文件中的代码展示出来，大家是看不懂的，缺少很多其他文件中的代码，代码也是无法直接运行的，还是要具体结合整个项目源码看才行。
所以，综上所述，给每个案例添加类似点击展开代码的功能是毫无意义的。
